### ISSUE TITLE
The classes in validation log using VisA dataset

### ISSUE THREAD

**Issue by littledeep** [lewandofskee/DiAD#28]
![Image](https://github.com/lewandofskee/DiAD/assets/42002469/52f3daa1-4b4d-40fd-9296-e99d9bd0bf48)
when I train VisA dataset, the classes in validation log is the same as MVtecad. I can not find the config. Can you help me find how to modify the config.

**Comment by littledeep** [comment]
![image](https://github.com/lewandofskee/DiAD/assets/42002469/aecd28a4-fcdc-4ae4-8b15-9f28c93931ea)
When I train the dataset the same time, the classes is included both the dataset.

**Comment by littledeep** [comment]
I stop the training of VisA Dataset, but the validation classes is 27 classes, which includes the classes in VisA and MVtecad.

**Comment by lewandofskee** [comment]
The 'npz_result' folder is generated during the validation process and the files in it are updated at each validation. This happens because the 'npz_result' folder retains the .npz files of the MvtecAD dataset after you have trained it. You need to empty the 'npz_result' folder before training or testing the VisA dataset.

**Comment by littledeep** [comment]
Thanks！
