### ISSUE TITLE
ModuleNotFoundError: No module named 'taming.modules.losses'？

### ISSUE THREAD

**Issue by PENGYUN906** [lewandofskee/DiAD#35]
第一个问题，执行时，报了这个导入错误，发现源代码中taming文件下没有这几个文件，求解答。
第二个问题，在第三步finetune Autoencoders时，下载了预训练的模型kl-f8.zip，并移动到`./models/autoencoders.ckpt`，请问是将kl-f8.zip解压后并重新命名为autoencoders.ckpt移动到‘./models’下吗？

**Comment by lewandofskee** [comment]
1. Sorry I ignored this installation package. Please install the corresponding package `pip install taming_transformers`.
2. Yes, exactly.

**Comment by HANLE321** [comment]
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
执行第四步，建立模型的时候，总出现这个这个错误，有没有什么建议
