### ISSUE TITLE
Rec?

### ISSUE THREAD

**Issue by asdfgmonkey** [lewandofskee/DiAD#38]
I copied your code, but the Rec picture I got is still broken (not as well fixed as in the paper), why? Is it because my data set is only 1000 and I can't feed it?

**Comment by lewandofskee** [comment]
Thank you for your attention. We have not tried training and reconstruction of small-scale data sets, but I think the reconstruction effect can be enhanced by increasing training epochs.

**Comment by HANLE321** [comment]
你在复现程序过程中有没有出现以下错误，这是我在运行第四步建立模型时出现的错误，您能给一些指导意见吗(Have you encountered the following errors during the process of reproducing the program? This is the error I encountered during the fourth step of building the model. Can you provide some guidance)
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**Comment by lewandofskee** [comment]
@HANLE321 I think it may be that your server is not connecting to huggingface.co, causing your deployment to fail. You can refer to this [blog](https://blog.csdn.net/SuperB666/article/details/132826492) as well as this [issue](https://github.com/CompVis/stable-diffusion/issues/90) to try to fix it.

**Comment by HANLE321** [comment]
@lewandofskeeIt shouldn't be a network issue, as this website may have a path issue when it can be opened in the browser. I have previously dealt with it based on the article you recommended, but it did not work，I don't know how to handle it now
